### ISSUE TITLE
Arbol de apropiaciones - Revisar el detalle de la carga ya que no actualiza al ingresar una nueva apropiación

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente_angular_8#10]
- [x]  Revisar el detalle de la carga ya que no actualiza al ingresar una nueva apropiación

**Comment by davidmm07** [comment]
Se revisa y hay problemas con CORS, solo pasa en el ambiente de pruebas (Dev) ![](https://i.imgur.com/lunYpLz.png)

**Comment by davidmm07** [comment]
Tarea terminada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
tarea revisada y se puede evidenciar en la versión desplegada sobre el servidor de pruebas

Proceeding to close Issue 👾
