### ISSUE TITLE
**presupuesto cliente angular 8** Migración código para la visualización del arbol de rubros, y creación del rubro - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/presupuesto_cliente_angular_8#11]
- [x] Corrección interface rubros
- [x] Migración módulos rubros

**Comment by miguelramirez93** [comment]
Se añaden funcionalidades de armado de arbol, edición y eliminado de nodos en el cliente de la versión anterior y luego se migra a esta version 
- (https://github.com/udistrital/presupuesto_cliente/commit/e74162672bbdc6612b448ef4de00fbd22f49d835)
- (https://github.com/udistrital/presupuesto_cliente/commit/54a42b958aaeb882f0ce99c4178ca71a4de6c495)
- (https://github.com/udistrital/presupuesto_cliente/commit/bb4735c2f58ad146184702ea329d7be6e480cc58)
- (https://github.com/udistrital/presupuesto_cliente/commit/9d8d750213b20a87b5af44f20e77341a8ab30154)

**Comment by miguelramirez93** [comment]
se realiza pull request @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Listo Miguel, 
tarea revisada y en la versión desplegada sobre el .254

Para finalizar los ajustes de creación de rubro, manejemolo en un nuevo issue .
Buen trabajo

Proceeding to close Issue :space_invader:

**Comment by Soulfilip-UD** [comment]
La migración fue exitosa y el issue esta finalizado en un 100%, ya se pueden visualizar los cambios en la versión desplegada sobre el servidor de pruebas
