### ISSUE TITLE
**presupuesto_cliente** Implementar interceptor que adjunta el access token - 5 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/presupuesto_cliente_angular_8#18]
- [x] añadir interceptor para agregar toekn en las peticiones

**Comment by miguelramirez93** [comment]
La tarea se cumplio y ya se encuentra integrada a la rama dev

**Comment by Soulfilip-UD** [comment]
perfecto, revisada y se finaliza la tarea

Proceeding to close Issue :space_invader:
