### ISSUE TITLE
Pre-carga de arbol de pre-apropiaciones (cliente) - 8 horas - David

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente_angular_8#22]
- [x] Generar función que cargue el arbol de preasignación inicial por vigencia.
- [x] Conectar con api plan_cuentas_mongo.

**Comment by davidmm07** [comment]
Tarea terminada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
tarea revisada y se puede evidenciar en la versión desplegada sobre el servidor de pruebas

Proceeding to close Issue 👾
