### ISSUE TITLE
Migración cliente Angular Ngx-Admin 8 - Autenticación por medio de wso2, libreria y configuración de los entornos

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente_angular_8#3]
- [x] Autenticación por medio de wso2
- [x] Implementar Libreria y configuración de los entornos

**Comment by davidmm07** [comment]
Tarea terminada @Soufilip

**Comment by Soulfilip-UD** [comment]
Tarea revisada y se depliega y funciona en los 2 ambientes

Proceeding to close Issue :space_invader:
