### ISSUE TITLE
Crear nuevo repositorio del proyecto a trabajar en angular 8, con la plantilla inicial de ngx-admin

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente_angular_8#7]
- [x] Crear repositorio tomando como base el proyecto de ngx-admin en la version 8

**Comment by davidmm07** [comment]
Se crea repositorio https://github.com/udistrital/presupuesto_cliente_angular_8 y accedemos al 10.20.0.254/presupuesto para el ambiente de pruebas en (dev)

**Comment by davidmm07** [comment]
Se adjunta PR #1 #2

**Comment by davidmm07** [comment]
Tarea finalizada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea revisada y finalizda, se reviso en la versión desplegada 

Proceeding to close Issue :space_invader:
