### ISSUE TITLE
Conectar Menu de el cliente con el api de configuración en el repositorio de presupuesto

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente_angular_8#8]
- [x] Realizar la implementacion de Los menus del cliente de presupuesto
- [x] Realizar la integración con el API de Configuración

**Comment by davidmm07** [comment]
PR #16 #15 Tarea terminada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Afirmativo, la tarea se reviso y está finalizada y en la versión desplegada

Proceeding to close Issue :space_invader:
