### ISSUE TITLE
Migración del código para la visualización del arbol de apropiaciones y creación de apropiación - David

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente_angular_8#9]
- [x] Migración del código para la visualización del arbol de apropiaciones.
- [x] Migración de la creación de apropiación.

**Comment by davidmm07** [comment]
PR #17 queda pendiente los registros POST por error de CORS en el ambiente de pruebas (dev)
![Screenshot_2019-08-15_15-20-48](https://user-images.githubusercontent.com/15944053/63176954-83823580-c00c-11e9-96c5-9c5982e01018.png)

**Comment by Soulfilip-UD** [comment]
Listo! migraci{on correcta
dejemos la creación de la apropiación en un nuevo Issue 

tarea finalizada 
Proceeding to close Issue :space_invader:
